config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'videos/search', to: 'videos#search'
  # get 'videos/:id', to: 'videos#show', as: 'video'
  resources :videos, only: :show do
    resources :comments
  end
  root to: 'videos#index'

  get 'user/:id/interests', to: 'users#interests', as: 'user_interests'
  # get ':id' always last line of roots
  get 'user/:id', to: 'users#show', as: 'user_profile'

  post 'user/recieve_interest_choices', to: 'users#recieve_interest_choices'
  resources :histories, only: :update
  post 'user/skill_scores', to: 'users#skill_scores'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :histories, dependent: :destroy
  has_many :video_categories, dependent: :destroy
  has_many :sub_categories, through: :video_categories
  has_many :super_categories, through: :sub_categories
  has_many :comments, dependent: :destroy

  validates :youtube_id, uniqueness: true, presence: true, format: { with: /\A.{11}\z/ }
  validates :minimum_age, presence: true

  include PgSearch

  pg_search_scope :global_search,
    against: [ :title, :channel ],
    associated_against: {
      sub_categories: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_video, only: [:show]

  def index
    if user_signed_in?
    #   # ... current_user.scores
    # else
      # @videos = Video.all
      best_scores = current_user.skill_scores.order(skill_score: :DESC).first(2)
      @videos = []
      best_scores.each do |score|
        if score.sub_category.videos.exists?
          @videos << score.sub_category.videos.first(4) # videos
        end
      end
      # Flatten and uniq if array not empty
      if @videos.any?
        @videos.flatten!.uniq!
      else
        @videos = []
      end

    end

      # @videos = videos.
      # @videos = Video.find()
      # current_user.sub_categories.each do |subcategory|
      #   @recommended_videos = subcategory.skill_scores.order_by{ |score| score.skill_scores}
      # end
      # raise
      @sub_categories = SubCategory.all
    # end
  end

  def show
    @videos = Video.all
    @history = get_or_create_history
    @video_categories = VideoCategory.where("video_id = #{@video.id}")
    @comments = Comment.where(video: @video)
    increment_skill_score if user_signed_in?
    @display_calculator = show_calculator?(@video)
    @suggested_videos = get_suggested_videos(@video)
    # increment_interest_score if user_signed_in?
  end

  def search
    if params[:query].present?
      @videos = Video.global_search(params[:query])
      @query = params[:query]
      # flash[:notice] = "Résultats pour '#{@query}.'"
    else
     flash[:alert] = "Nous mettons nos catégories à jour, merci de réessayer ta recherche plus tard."
     redirect_to root_path
    end
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def get_or_create_history
    if user_signed_in?
      history = History.find_by(user: current_user, video: @video)
      if history == nil
        History.create(video: @video, user: current_user)
      else
        history.touch
        history
      end
    end
  end

  def get_suggested_videos(video)
    if video.sub_categories.any?
      suggested_videos = []
      video.sub_categories.each do |sub_category|
        video_tags = sub_category.video_categories.order(relevance: :desc).limit(4)
        video_tags.each { |tag| suggested_videos << tag.video }
      end
      suggested_videos.shuffle
    else
      Video.all.shuffle.first(8)
    end
  end

  def increment_interest_score
    # Iterate through unique super_categories of video
    @video.super_categories.uniq.each do |super_category|
      # Get score that belongs to user for super category
      score = super_category.scores.find_by(user: current_user)

      # ====================================================
      # Must create interest scores automatically on sign_up
      # ====================================================

      # Get current viewed_videos score
      new_viewed_videos_score = (score.viewed_videos += 1)
      # Get current interest score
      new_interest_score = (score.interest_score += 1)
      # Increment viewed_videos or interest score score by one
      score.update(viewed_videos: new_viewed_videos_score, interest_score: new_interest_score)
    end
  end

  def increment_skill_score
    # Iterate through unique super_categories of video
    @video.sub_categories.uniq.each do |sub_category|
      # Get score that belongs to user for sub category
      score = sub_category.skill_scores.find_by(user: current_user)
      # Get current viewed_videos score
      new_viewed_videos_score = (score.viewed_videos += 1)
      # Get current skill score
      new_skill_score = (score.skill_score += 1)
      # Increment viewed_videos or skill score score by one
      score.update(viewed_videos: new_viewed_videos_score, skill_score: new_skill_score)
    end
  end

  def show_calculator?(video)
    tech = SubCategory.find_by(name: 'Technologie')
    astronomie = SubCategory.find_by(name: 'Astronomie & Cosmologie')
    if (video.sub_categories.include? tech) || (video.sub_categories.include? astronomie)
      return true
    else
      return false
    end
  end
end

app/views/videos/_calculater.html.erb
<div class="color">
  <div class="main">
    <form name="form">
      <input class="textview form-control" name="textview">
    </form>
    <table>
      <tr>
      <td><input class="button" type="button" value="C" onclick="clean()"></td>
      <td><input class="button" type="button" value="<" onclick="back()"></td>
      <td><input class="button" type="button" value="/" onclick="insert('/')"></td>
      <td><input class="button" type="button" value="x" onclick="insert('*')"></td>
    </tr>

    <tr>
      <td><input class="button" type="button" value="7" onclick="insert(7)"></td>
      <td><input class="button" type="button" value="8" onclick="insert(8)"></td>
      <td><input class="button" type="button" value="9" onclick="insert(9)"></td>
      <td><input class="button" type="button" value="-" onclick="insert('-')"></td>
    </tr>

    <tr>
      <td><input class="button" type="button" value="4" onclick="insert(4)"></td>
      <td><input class="button" type="button" value="5" onclick="insert(5)"></td>
      <td><input class="button" type="button" value="6" onclick="insert(6)"></td>
      <td><input class="button" type="button" value="+" onclick="insert('+')"></td>
      </tr>

      <tr>
        <td><input class="button" type="button" value="1" onclick="insert(1)"></td>
        <td><input class="button" type="button" value="2" onclick="insert(2)"></td>
        <td><input class="button" type="button" value="3" onclick="insert(3)"></td>
        <td rowspan="5"><input class="button equals" type="button" value="=" onclick="equal()"></td>
        </tr>

        <tr>
          <td colspan="2"><input class="button insert" type="button" value="0" onclick="insert(0)"></td>
          <td><input class="button" type="button" value="." onclick="insert('.')"></td>
          </tr>
    </table>
  </div>
</div>

<script>function insert(num) {
  document.form.textview.value = document.form.textview.value+num
}

function equal() {
  let exp = document.form.textview.value;
  if(exp) {
      document.form.textview.value = eval(exp);
  }
}

function clean(){
  document.form.textview.value = "";
}

function back(){
  let exp = document.form.textview.value;
  document.form.textview.value = exp.substring(0,exp.length-1);
}
</script>

app/views/videos/_iframe_img.html.erb
<!-- <iframe width="560" height="315" src="https://img.youtube.com/vi/#{youtube_id}/0.jpg" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe> -->


  <div class="row">
    <% videos.each do |video| %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 pad-top-bottom-15">
        <%= link_to video_path(video) do %>
          <div class="card">
            <div class="card-img" style="background-image: url('https://img.youtube.com/vi/<%= video.youtube_id %>/0.jpg')">
              <div class="play-button"><i class="fas fa-play-circle"></i></div>
            </div>
            <div class="card-content-responsive-wrapper-big">
              <div class="card-content">
                <div class="details">
                  <p><i class="far fa-comments"></i></p>
                  <p><i class="far fa-eye"></i></p>
                  <p><i class="far fa-clock"></i> <%= video.duration_seconds / 60 %>:<%= "%.2i" %(video.duration_seconds % 60) %> </p>
                </div>
                <div class="description">
                  <p><%= video.title[0..40] %></p>
                </div>
                <div class="footer">
                  <p><%= video.channel[0..20] %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/videos/_iframe_img_6.html.erb
<div class="row">
    <% videos.each do |video| %>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-2 pad-top-bottom-15">
        <%= link_to video_path(video) do %>
          <div class="card">
            <div class="card-img" style="background-image: url('https://img.youtube.com/vi/<%= video.youtube_id %>/0.jpg')">
              <div class="play-button"><i class="fas fa-play-circle"></i></div>
            </div>
            <div class="card-content-responsive-wrapper-small">
              <div class="card-content">
                <div class="fixed-height-20">
                  <div class="details">
                    <p><i class="far fa-comments"></i></p>
                    <p><i class="far fa-eye"></i></p>
                    <p><i class="far fa-clock"></i> <%= video.duration_seconds / 60 %>:<%= "%.2i" %(video.duration_seconds % 60) %> </p>
                  </div>
                </div>
                <div class="description">
                  <p><%= video.title[0..40] %></p>
                </div>
                <div class="footer">
                  <p><%= video.channel[0..20] %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/videos/_iframe_video.html.erb
<!-- <div class="video-wrapper">
  <div class="container">
     <iframe   height="543" src="https://www.youtube.com/embed/<%= video.youtube_id %>?rel=0" frameborder="0" allow="autoplay; encrypted-media"     allowfullscreen>

    </iframe>
  </div>
</div> -->

<!-- <div class="container">
  <div class="iframe-container">
    <iframe src="https://www.youtube.com/embed/<%= video.youtube_id %>?rel=0" allowfullscreen></iframe>
  </div>
</div> -->


<div class="container">
  <div class="grid-show">
    <div class="wrapper-row">
      <div class="row">
        <div class="col-xs-12 col-md-12">
          <div class="iframe-container">
            <iframe src="https://www.youtube.com/embed/<%= video.youtube_id %>?rel=0" allowfullscreen></iframe>
          </div>
            <div class="bottom-video">
              <div class="video-details-wrapper">

                <p><i class="far fa-comments"> 12</i></p>
                <p><i class="far fa-eye"> 2</i></p>
                <div class="icon-wrapper"><i class="far fa-clock"></i> <%= @video.duration_seconds / 60 %>:<%= "%.2i" %(@video.duration_seconds % 60) %>
                </div>
              </div>
              <div class="verified-wrapper">
                <% if @video.verified == true  %>
                  <div class="verified">
                    <i class="fas fa-check-circle"><p>Vidéo vérifiée</p></i>
                  </div>
                <% end %>
                <% if @video.introduction == true  %>
                  <div class="verified">
                    <i class="fas fa-info-circle"><p>Vidéo d'introduction</p></i>

                  </div>
                <% end %>
                <% if  @video.pro == true  %>
                  <div class="verified">
                    <i class="fas fa-key"><p>Vidéo professionnalisante</p></i>
                  </div>
                <% end %>
              </div>
              <hr>
              <div id="accordion">
                <div class="card-header" id="headingTwo">
                  <h5 class="mb-0">
                    <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      Description ...
                    </button>
                  </h5>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                  <div class="card-body video-content">
                    <%= @video.description %>
                  </div>
                </div>
              </div>
              <hr>
              <%= @comments.first.text %>
            </div>
          </div>
        </div>
      </div>
      <div class="recomandation">
        <%= render 'video_recommandation' %>
      </div>
    </div>
  </div>
</div>

app/views/videos/_jumbotrone.html.erb
<!-- <div class="jumbotron"> -->
  <div class="jumbotrone-wrapper">
    <div class="jumbotrone-head">
      <div class="container ">
        <div class="max-width-content"><h1>Découvre ton chemin.</h1>
          <p>Trouve ce qu'il te plait. Vas plus loin en dévoilant les sujets qui t'intéressent.</p>
          <%= link_to "S'inscrire", new_user_registration_path, class: 'btn btn-primary btn-jumbotrone'  %></div>
      </div>
    </div>
  </div>
<!-- </div> -->

app/views/videos/_suggested_videos.html.erb
<div class="suggested-videos light-star-card-border-top-no-hover background-white">
  <h4 class="margin-top-0">Ce que tu pourrais aimer :</h4>
  <div class="row">
    <% @suggested_videos.each do |video| %>
      <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3 pad-top-bottom-15">
        <%= link_to video_path(video) do %>
          <div class="card">
            <div class="card-img" style="background-image: url('https://img.youtube.com/vi/<%= video.youtube_id %>/0.jpg')">
              <div class="play-button"><i class="fas fa-play-circle"></i></div>
            </div>
            <div class="card-content-responsive-wrapper-small">
              <div class="card-content">
                <div class="fixed-height-20">
                  <div class="details">
                    <p><i class="far fa-comments"></i></p>
                    <p><i class="far fa-eye"></i></p>
                    <p><i class="far fa-clock"></i> <%= video.duration_seconds / 60 %>:<%= "%.2i" %(video.duration_seconds % 60) %> </p>
                  </div>
                </div>
                <div class="description">
                  <p><%= video.title[0..40] %></p>
                </div>
                <div class="footer">
                  <p><%= video.channel[0..20] %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/videos/_video_recommandation.html.erb
<div class="row">
    <% @videos.each do |video| %>
      <div class="col-xs-12 pad-bottom-30">
        <%= link_to video_path(video) do %>
          <div class="small-card">
            <div class="small-card-img" style="background-image: url('https://img.youtube.com/vi/<%= video.youtube_id %>/0.jpg')">
              <div class="play-button"><i class="fas fa-play-circle"></i></div>
            </div>
            <div class="small-card-content">
              <div class="small-details">
                <p><i class="far fa-comments"></i></p>
                <p><i class="far fa-eye"></i></p>
                <p><i class="far fa-clock"></i> <%= video.duration_seconds / 60 %>:<%= "%.2i" %(video.duration_seconds % 60) %> </p>
              </div>
              <div class="small-description">
                <p><%= video.title %></p>
              </div>
              <div class="small-footer">
                <p><%= video.channel %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/videos/index.html.erb
<% if user_signed_in? %>
  <div class="padding-15"></div>
  <div class="container">
    <% if @videos.any? %>
      <h3>Ce que tu pourrais aimer...</h3>
      <%= render 'iframe_img', videos: @videos %>
   <% end %>
   <% @sub_categories.each do |category| %>
      <% next if category.videos.empty? %>
        <h4><%= category.name %></h4>
        <%= render 'iframe_img_6', videos: category.videos.first(6) %>
      <% end %>
  </div>
<% else %>
  <%= render 'jumbotrone' %></div>
  <div class="container">
  <div class="padding-15"></div>
    <% @sub_categories.each do |category| %>
      <% next if category.videos.empty? %>
      <h4><%= category.name %></h4>
          <%= render 'iframe_img_6', videos: category.videos.first(6) %>
    <% end %>
  </div>
<% end %>

app/views/videos/search.html.erb
<div class="container">
  <div class="padding-15"></div>
  <h4 style="margin-left: 15px;">Résultats pour '<%= @query %>'</h4>
  <% if @videos.count != 0 %>
    <!-- <h4 class="text-center">Résultats</h4> -->
    <div class="container">
      <%= render 'iframe_img', videos: @videos %>

    </div>
  <% else %>
    <% flash[:alert] = "Nous mettons nos catégories à jour, merci de réessayer ta recherche plus tard." %>
  <% end %>
</div>

app/views/videos/show.html.erb
<div class="padding-15"></div>
<div class="container">
  <div class="grid-show">
    <div class="wrapper-row">
      <div class="row">
        <div class="col-xs-12 col-md-12">
          <div class="large-video-card-wrapper light-star-card-no-hover">
            <div class="iframe-container">
              <iframe src="https://www.youtube.com/embed/<%= @video.youtube_id %>?rel=0" allowfullscreen></iframe>
            </div>
              <div class="bottom-video">
                <div class="video-details-wrapper">
                  <div class="categories-wrapper">
                    <% @video.sub_categories.each do |sub_category| %>
                      <span class="category-label"><%= sub_category.name %></span>
                    <% end %>
                  </div>
                  <div class="stats-wrapper">
                    <div><i class="far fa-comments"> 12</i></div>
                    <div><i class="far fa-eye"> 2</i></div>
                    <div class="icon-wrapper"><i class="far fa-clock"></i> <%= @video.duration_seconds / 60 %>:<%= "%.2i" %(@video.duration_seconds % 60) %>
                    </div>
                  </div>
                </div>
                <h1 class="h4 video-title"><%= @video.title %></h1>
                <div id="accordion">
                  <div class="card-header" id="headingTwo">
                    <h5 class="mb-0">
                      <button class="btn-see-description collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Voir la déscription...
                      </button>
                    </h5>
                  </div>
                  <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                    <div class="card-body video-content">
                      <%= @video.description %>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>

      <div class="recomandation light-star-card-no-hover">
        <div class="tools-menu">
          <ul class="nav nav-tabs tools-tab-list">
            <li role="presentation" id="tab-1" class="tools-menu-tab active">Notes</li>
            <% if @display_calculator %>
              <li role="presentation" id="tab-2" class="tools-menu-tab ">Calculatrice</li>
            <% end %>
          </ul>
          <% if user_signed_in? %>
            <div id="tab-body-1" class="tools-menu-tab-body">
             <%= simple_form_for @history, remote: true, method: :patch do |f| %>
               <%= f.input :note, as: :text, label: false, :input_html => {style: 'height:350px;'} %>
               <%= f.input :id, as: :hidden %>
               <div id="updated"><%= f.button :submit, 'Sauvegarde Notes', class: 'btn btn-success' %>
                <div ></div>
               </div>
              <% end %>
            </div>
          <% else %>
            <div id="tab-body-2" class="tools-menu-tab-body">
              <%= link_to t(".sign_in", default: "Connecte-toi pour prendre des notes."), new_user_session_path, class: "light-star-link" %>
            </div>
          <% end %>
          <% if @display_calculator %>
            <div id="tab-body-2" class="tools-menu-tab-body hidden">
              <%= render 'calculater' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="grid-show">
      <div class="suggested-videos-wrapper">
        <%= render 'suggested_videos' %>
      </div>
      <div class="suggested-videos-space-holder"></div>
    </div>
  </div>
</div>