config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'videos/search', to: 'videos#search'
  # get 'videos/:id', to: 'videos#show', as: 'video'
  resources :videos, only: :show do
    resources :comments
  end
  root to: 'videos#index'

  get 'user/:id/interests', to: 'users#interests', as: 'user_interests'
  # get ':id' always last line of roots
  get 'user/:id', to: 'users#show', as: 'user_profile'

  post 'user/recieve_interest_choices', to: 'users#recieve_interest_choices'
  resources :histories, only: :update
  post 'user/skill_scores', to: 'users#skill_scores'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert borderless-no-radius alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert borderless-no-radius alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>

    <div class="logo-responsive"></div>
  <% end %>

  <%= form_tag videos_search_path, class: "search-bar-wrapper", method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control devise-form-control-search",
      placeholder: "trouver une vidéo..."
    %>
    <span class="input-group-btn">
      <%= button_tag(type: "submit", class: "btn btn-search btn-default") do %>
        <i class="text-secondary fas fa-search"></i>
      <% end %>
    </span>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <div class="navbar-wagon-item">
        <%= link_to t(".sign_out", default: "Se déconnecter"), destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to user_profile_path(current_user.slug) do %>

        <%= cl_image_tag current_user.photo_id, width: 100, height: 100, crop: :thumb, gravity: :face, class: "avatar", id: "navbar-wagon-menu"%>

        <% end %>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_up", default: "S'inscrire"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li><%= link_to t(".profile", default: "Profile"), user_profile_path(current_user.slug), class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to t(".sign_out", default: "Se déconnecter"), destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% else %>
          <li><%= link_to t(".sign_up", default: "S'inscrire"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>